### ISSUE TITLE
go get doesn't install the binary to $GOPATH/bin

### ISSUE THREAD

**Issue by smw1218** [sqs/used#1]
followed directions in readme... didn't work. I can't remember how this works but I think you need to put your main package in the root of the repo?

**Comment by jtorvald** [comment]
I've the same issue. I ran the install: go get... and binary is nowhere to be found. The go src dir only contains:

`go/src/sourcegraph.com/sqs/
go/src/sourcegraph.com/sqs//goreturns
go/src/sourcegraph.com/sqs//goreturns/.git
go/src/sourcegraph.com/sqs//goreturns/.git/branches
go/src/sourcegraph.com/sqs//goreturns/.git/config
go/src/sourcegraph.com/sqs//goreturns/.git/description
go/src/sourcegraph.com/sqs//goreturns/.git/HEAD
go/src/sourcegraph.com/sqs//goreturns/.git/hooks
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/applypatch-msg.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/commit-msg.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/post-update.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/pre-applypatch.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/pre-commit.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/pre-push.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/pre-rebase.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/prepare-commit-msg.sample
go/src/sourcegraph.com/sqs//goreturns/.git/hooks/update.sample
go/src/sourcegraph.com/sqs//goreturns/.git/index
go/src/sourcegraph.com/sqs//goreturns/.git/info
go/src/sourcegraph.com/sqs//goreturns/.git/info/exclude
go/src/sourcegraph.com/sqs//goreturns/.git/logs
go/src/sourcegraph.com/sqs//goreturns/.git/logs/HEAD
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs/heads
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs/heads/master
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs/remotes
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs/remotes/origin
go/src/sourcegraph.com/sqs//goreturns/.git/logs/refs/remotes/origin/HEAD
go/src/sourcegraph.com/sqs//goreturns/.git/objects
go/src/sourcegraph.com/sqs//goreturns/.git/objects/info
go/src/sourcegraph.com/sqs//goreturns/.git/objects/pack
go/src/sourcegraph.com/sqs//goreturns/.git/objects/pack/pack-18bbefbdc20a93249f6a63c36e653a0cc798356d.idx
go/src/sourcegraph.com/sqs//goreturns/.git/objects/pack/pack-18bbefbdc20a93249f6a63c36e653a0cc798356d.pack
go/src/sourcegraph.com/sqs//goreturns/.git/packed-refs
go/src/sourcegraph.com/sqs//goreturns/.git/refs
go/src/sourcegraph.com/sqs//goreturns/.git/refs/heads
go/src/sourcegraph.com/sqs//goreturns/.git/refs/heads/master
go/src/sourcegraph.com/sqs//goreturns/.git/refs/remotes
go/src/sourcegraph.com/sqs//goreturns/.git/refs/remotes/origin
go/src/sourcegraph.com/sqs//goreturns/.git/refs/remotes/origin/HEAD
go/src/sourcegraph.com/sqs//goreturns/.git/refs/tags
go/src/sourcegraph.com/sqs//goreturns/_samples
go/src/sourcegraph.com/sqs//goreturns/_samples/a.go
go/src/sourcegraph.com/sqs//goreturns/_samples/b.go
go/src/sourcegraph.com/sqs//goreturns/goreturns.go
go/src/sourcegraph.com/sqs//goreturns/LICENSE
go/src/sourcegraph.com/sqs//goreturns/README.md
go/src/sourcegraph.com/sqs//goreturns/returns
go/src/sourcegraph.com/sqs//goreturns/returns/fix.go
go/src/sourcegraph.com/sqs//goreturns/returns/fix_test.go
go/src/sourcegraph.com/sqs//goreturns/returns/index.go
go/src/sourcegraph.com/sqs//goreturns/returns/returns.go
go/src/sourcegraph.com/sqs//goreturns/screencast.gif
`

**Comment by damienstanton** [comment]
I experienced this as well, and fixed it on my fork by switching to a `lib` style layout instead of `cmd`.

**Comment by sqs** [comment]
Thanks. Fixed in https://github.com/sqs/used/commit/c5a513e39809172352e3b83a250da07b7ef1601f.
